# Generated by Django 3.1 on 2020-08-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='energy',
            field=models.IntegerField(default=0),
        ),
    ]
